[project]
name = "sqlengine-lite"
version = "2.2.2"
description = "Cute sqlite3 wrapper for sql tables"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]


[tool.setuptools.package-dir]
"" = "src"

[tool.setuptools.packages.find]
where = ["src"]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "black==26.5.1",
    "pydoc-markdown>=4.8.2",
]

[project.urls]
Homepage = "https://github.com/suffermuffin/SQL-Engine"
Repository = "https://github.com/suffermuffin/SQL-Engine.git"
Documentation = "https://github.com/suffermuffin/SQL-Engine/blob/main/docs/index.md"
