[project]
name = "sqlengine"
version = "2.1.0"
description = "Cute sqlite3 wrapper for sql tables"
readme = "README.md"
requires-python = ">=3.12"
dependencies = []

[tool.setuptools]
packages = ["sqlengine"]

[tool.setuptools.package-dir]
"" = "src"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/suffermuffin/SQL-Engine"
Repository = "https://github.com/suffermuffin/SQL-Engine.git"
Documentation = "https://github.com/suffermuffin/SQL-Engine/blob/main/docs/index.md"